In [1]:
import numpy as np

In [2]:
i=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])

In [3]:
i.size

20

In [4]:
i.dtype

dtype('int32')

In [5]:
i.itemsize

4

In [7]:
i.sum()

3810

In [9]:
i[2]-=10
print(i)

[[100 200 150 300]
 [ 50  60  40  80]
 [280 380 330 480]
 [200 250 220 270]
 [ 80  90  70 100]]


In [10]:
i+=20
print(i)

[[120 220 170 320]
 [ 70  80  60 100]
 [300 400 350 500]
 [220 270 240 290]
 [100 110  90 120]]


In [11]:
i[0:6,1]*=2
print(i)

[[120 440 170 320]
 [ 70 160  60 100]
 [300 800 350 500]
 [220 540 240 290]
 [100 220  90 120]]


In [12]:
i[0:6,1]*=2
print(i)

[[ 120  880  170  320]
 [  70  320   60  100]
 [ 300 1600  350  500]
 [ 220 1080  240  290]
 [ 100  440   90  120]]


In [13]:
np.sum(i,axis=0)

array([ 810, 4320,  910, 1330])

In [14]:
np.max(i,axis=0)

array([ 300, 1600,  350,  500])

In [15]:
np.sum(i,axis=1)

array([1490,  550, 2750, 1830,  750])

In [16]:
np.sum(i,axis=1)

array([1490,  550, 2750, 1830,  750])

In [17]:
np.min(i,axis=1)

array([120,  60, 300, 220,  90])

In [18]:
np.mean(i,axis=1)

array([372.5, 137.5, 687.5, 457.5, 187.5])

In [21]:
np.mean(i,axis=0)

array([162., 864., 182., 266.])

In [24]:
i[1]

array([ 70, 320,  60, 100])

In [25]:
i[:,3]

array([320, 100, 500, 290, 120])

In [26]:
i[0:3,0:2]

array([[ 120,  880],
       [  70,  320],
       [ 300, 1600]])

In [27]:
i[3:6,2:4]

array([[240, 290],
       [ 90, 120]])

In [28]:
i[0,0]
i[3,2]

240

In [29]:
i[1, 3] = 100
print(i)

[[ 120  880  170  320]
 [  70  320   60  100]
 [ 300 1600  350  500]
 [ 220 1080  240  290]
 [ 100  440   90  120]]
